//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Ready4Balfolk.UI.Resources;

using System.Globalization;
using System.Resources;

public static class UiStrings
{
    private static ResourceManager? _resourceManager;

    public static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager(
            "Ready4Balfolk.UI.Resources.UiStrings",
            typeof(UiStrings).Assembly);

    public static CultureInfo? Culture { get; set; }

    // MainWindow
    public static string MainWindow_Title =>
        ResourceManager.GetString("MainWindow_Title", Culture)!;

    public static string MainWindow_Back =>
        ResourceManager.GetString("MainWindow_Back", Culture)!;

    public static string MainWindow_Settings =>
        ResourceManager.GetString("MainWindow_Settings", Culture)!;

    public static string MainWindow_Help =>
        ResourceManager.GetString("MainWindow_Help", Culture)!;

    // Toolbar
    public static string Playback_PlayLabel =>
        ResourceManager.GetString("Playback_PlayLabel", Culture)!;

    public static string Playback_PauseLabel =>
        ResourceManager.GetString("Playback_PauseLabel", Culture)!;

    public static string Playback_RestartLabel =>
        ResourceManager.GetString("Playback_RestartLabel", Culture)!;

    public static string Playback_SkipLabel =>
        ResourceManager.GetString("Playback_SkipLabel", Culture)!;

    public static string Playback_ClearLabel =>
        ResourceManager.GetString("Playback_ClearLabel", Culture)!;

    public static string QueueToolbar_HistoryLabel =>
        ResourceManager.GetString("QueueToolbar_HistoryLabel", Culture)!;

    public static string QueueToolbar_RandomLabel =>
        ResourceManager.GetString("QueueToolbar_RandomLabel", Culture)!;

    public static string QueueToolbar_StopLabel =>
        ResourceManager.GetString("QueueToolbar_StopLabel", Culture)!;

    public static string QueueToolbar_DelayLabel =>
        ResourceManager.GetString("QueueToolbar_DelayLabel", Culture)!;

    public static string QueueToolbar_MessageLabel =>
        ResourceManager.GetString("QueueToolbar_MessageLabel", Culture)!;

    public static string QueueToolbar_RemoveLabel =>
        ResourceManager.GetString("QueueToolbar_RemoveLabel", Culture)!;

    public static string QueueToolbar_ClearLabel =>
        ResourceManager.GetString("QueueToolbar_ClearLabel", Culture)!;

    public static string Queue_MoveUpLabel =>
        ResourceManager.GetString("Queue_MoveUpLabel", Culture)!;

    public static string Queue_MoveDownLabel =>
        ResourceManager.GetString("Queue_MoveDownLabel", Culture)!;

    public static string HistoryToolbar_QueueLabel =>
        ResourceManager.GetString("HistoryToolbar_QueueLabel", Culture)!;

    public static string HistoryToolbar_ExportLabel =>
        ResourceManager.GetString("HistoryToolbar_ExportLabel", Culture)!;

    public static string HistoryToolbar_ClearLabel =>
        ResourceManager.GetString("HistoryToolbar_ClearLabel", Culture)!;

    public static string TrackCatalog_ClearSearchLabel =>
        ResourceManager.GetString("TrackCatalog_ClearSearchLabel", Culture)!;

    public static string MainWindow_BackLabel =>
        ResourceManager.GetString("MainWindow_BackLabel", Culture)!;

    public static string Queue_RefreshAutoTrackLabel =>
        ResourceManager.GetString("Queue_RefreshAutoTrackLabel", Culture)!;

    public static string Queue_KeepTrackLabel =>
        ResourceManager.GetString("Queue_KeepTrackLabel", Culture)!;

    public static string Toolbar_ExitLabel =>
        ResourceManager.GetString("Toolbar_ExitLabel", Culture)!;

    public static string Toolbar_HelpLabel =>
        ResourceManager.GetString("Toolbar_HelpLabel", Culture)!;

    public static string Toolbar_SettingsLabel =>
        ResourceManager.GetString("Toolbar_SettingsLabel", Culture)!;

    public static string Settings_ShowButtonText =>
        ResourceManager.GetString("Settings_ShowButtonText", Culture)!;

    public static string Settings_ShowButtonTextDescription =>
        ResourceManager.GetString("Settings_ShowButtonTextDescription", Culture)!;

    public static string Toolbar_Exit =>
        ResourceManager.GetString("Toolbar_Exit", Culture)!;

    public static string Toolbar_Help =>
        ResourceManager.GetString("Toolbar_Help", Culture)!;

    public static string Toolbar_Settings =>
        ResourceManager.GetString("Toolbar_Settings", Culture)!;

    // Settings
    public static string Settings_Title =>
        ResourceManager.GetString("Settings_Title", Culture)!;

    public static string Settings_MusicDirectory =>
        ResourceManager.GetString("Settings_MusicDirectory", Culture)!;

    public static string Settings_MusicDirectoryWatermark =>
        ResourceManager.GetString("Settings_MusicDirectoryWatermark", Culture)!;

    public static string Settings_Browse =>
        ResourceManager.GetString("Settings_Browse", Culture)!;

    public static string Settings_QueueCutoff =>
        ResourceManager.GetString("Settings_QueueCutoff", Culture)!;

    public static string Settings_QueueCutoffGrace =>
        ResourceManager.GetString("Settings_QueueCutoffGrace", Culture)!;

    public static string Settings_QueueCutoffDescription =>
        ResourceManager.GetString("Settings_QueueCutoffDescription", Culture)!;

    public static string Queue_CutoffPaused =>
        ResourceManager.GetString("Queue_CutoffPaused", Culture)!;

    public static string Settings_MaxQueueItems =>
        ResourceManager.GetString("Settings_MaxQueueItems", Culture)!;

    public static string Settings_DelayDuration =>
        ResourceManager.GetString("Settings_DelayDuration", Culture)!;

    public static string Settings_DelayDescription =>
        ResourceManager.GetString("Settings_DelayDescription", Culture)!;

    public static string Settings_PresentationDisplays =>
        ResourceManager.GetString("Settings_PresentationDisplays", Culture)!;

    public static string Settings_PresentationDescription =>
        ResourceManager.GetString("Settings_PresentationDescription", Culture)!;

    public static string Settings_AutoQueue =>
        ResourceManager.GetString("Settings_AutoQueue", Culture)!;

    public static string Settings_AutoQueueDescription =>
        ResourceManager.GetString("Settings_AutoQueueDescription", Culture)!;

    public static string Settings_AllowDuplicates =>
        ResourceManager.GetString("Settings_AllowDuplicates", Culture)!;

    public static string Settings_AllowDuplicatesDescription =>
        ResourceManager.GetString("Settings_AllowDuplicatesDescription", Culture)!;

    public static string Settings_ConfirmPlayback =>
        ResourceManager.GetString("Settings_ConfirmPlayback", Culture)!;

    public static string Settings_ConfirmPlaybackDescription =>
        ResourceManager.GetString("Settings_ConfirmPlaybackDescription", Culture)!;

    public static string Settings_Theme =>
        ResourceManager.GetString("Settings_Theme", Culture)!;

    public static string Settings_ThemeDescription =>
        ResourceManager.GetString("Settings_ThemeDescription", Culture)!;

    public static string Settings_Language =>
        ResourceManager.GetString("Settings_Language", Culture)!;

    public static string Settings_LanguageDescription =>
        ResourceManager.GetString("Settings_LanguageDescription", Culture)!;

    public static string Settings_Troubleshooting =>
        ResourceManager.GetString("Settings_Troubleshooting", Culture)!;

    public static string Settings_ExportLog =>
        ResourceManager.GetString("Settings_ExportLog", Culture)!;

    public static string Settings_ExportLogDescription =>
        ResourceManager.GetString("Settings_ExportLogDescription", Culture)!;

    public static string Settings_VersionFormat =>
        ResourceManager.GetString("Settings_VersionFormat", Culture)!;

    public static string Settings_SelectMusicDirectory =>
        ResourceManager.GetString("Settings_SelectMusicDirectory", Culture)!;

    public static string Settings_ExportLogTitle =>
        ResourceManager.GetString("Settings_ExportLogTitle", Culture)!;

    // Queue
    public static string Queue_StopMarker =>
        ResourceManager.GetString("Queue_StopMarker", Culture)!;

    public static string Queue_DelayMarker =>
        ResourceManager.GetString("Queue_DelayMarker", Culture)!;

    public static string Queue_MessageMarker =>
        ResourceManager.GetString("Queue_MessageMarker", Culture)!;

    public static string Queue_RefreshAutoTrack =>
        ResourceManager.GetString("Queue_RefreshAutoTrack", Culture)!;

    public static string Queue_KeepTrack =>
        ResourceManager.GetString("Queue_KeepTrack", Culture)!;

    public static string Queue_MoveUp =>
        ResourceManager.GetString("Queue_MoveUp", Culture)!;

    public static string Queue_MoveDown =>
        ResourceManager.GetString("Queue_MoveDown", Culture)!;

    public static string Queue_Empty =>
        ResourceManager.GetString("Queue_Empty", Culture)!;

    public static string Queue_ItemCount =>
        ResourceManager.GetString("Queue_ItemCount", Culture)!;

    public static string Queue_ItemCountPlural =>
        ResourceManager.GetString("Queue_ItemCountPlural", Culture)!;

    public static string Queue_PlaylistFinishesAt =>
        ResourceManager.GetString("Queue_PlaylistFinishesAt", Culture)!;

    public static string Queue_PlaylistHaltsAt =>
        ResourceManager.GetString("Queue_PlaylistHaltsAt", Culture)!;

    // Queue Toolbar
    public static string QueueToolbar_SwitchToHistory =>
        ResourceManager.GetString("QueueToolbar_SwitchToHistory", Culture)!;

    public static string QueueToolbar_QueueRandomTrack =>
        ResourceManager.GetString("QueueToolbar_QueueRandomTrack", Culture)!;

    public static string QueueToolbar_RequestStop =>
        ResourceManager.GetString("QueueToolbar_RequestStop", Culture)!;

    public static string QueueToolbar_RequestDelay =>
        ResourceManager.GetString("QueueToolbar_RequestDelay", Culture)!;

    public static string QueueToolbar_RequestMessage =>
        ResourceManager.GetString("QueueToolbar_RequestMessage", Culture)!;

    public static string QueueToolbar_RemoveSelected =>
        ResourceManager.GetString("QueueToolbar_RemoveSelected", Culture)!;

    public static string QueueToolbar_ClearQueue =>
        ResourceManager.GetString("QueueToolbar_ClearQueue", Culture)!;

    public static string QueueToolbar_ClearQueueTitle =>
        ResourceManager.GetString("QueueToolbar_ClearQueueTitle", Culture)!;

    public static string QueueToolbar_ClearQueueMessage =>
        ResourceManager.GetString("QueueToolbar_ClearQueueMessage", Culture)!;

    public static string QueueToolbar_ClearButton =>
        ResourceManager.GetString("QueueToolbar_ClearButton", Culture)!;

    public static string QueueToolbar_CancelButton =>
        ResourceManager.GetString("QueueToolbar_CancelButton", Culture)!;

    // History
    public static string History_NoHistory =>
        ResourceManager.GetString("History_NoHistory", Culture)!;

    public static string History_ItemCount =>
        ResourceManager.GetString("History_ItemCount", Culture)!;

    public static string History_ItemCountPlural =>
        ResourceManager.GetString("History_ItemCountPlural", Culture)!;

    public static string History_TypeTrack =>
        ResourceManager.GetString("History_TypeTrack", Culture)!;

    public static string History_TypeMessage =>
        ResourceManager.GetString("History_TypeMessage", Culture)!;

    public static string History_TypeDelay =>
        ResourceManager.GetString("History_TypeDelay", Culture)!;

    public static string History_TypeStop =>
        ResourceManager.GetString("History_TypeStop", Culture)!;

    public static string History_StartedAt =>
        ResourceManager.GetString("History_StartedAt", Culture)!;

    public static string History_StatusFinished =>
        ResourceManager.GetString("History_StatusFinished", Culture)!;

    public static string History_StatusSkipped =>
        ResourceManager.GetString("History_StatusSkipped", Culture)!;

    // History Toolbar
    public static string HistoryToolbar_SwitchToQueue =>
        ResourceManager.GetString("HistoryToolbar_SwitchToQueue", Culture)!;

    public static string HistoryToolbar_ExportHistory =>
        ResourceManager.GetString("HistoryToolbar_ExportHistory", Culture)!;

    public static string HistoryToolbar_ClearHistory =>
        ResourceManager.GetString("HistoryToolbar_ClearHistory", Culture)!;

    public static string HistoryToolbar_ClearHistoryTitle =>
        ResourceManager.GetString("HistoryToolbar_ClearHistoryTitle", Culture)!;

    public static string HistoryToolbar_ClearHistoryMessage =>
        ResourceManager.GetString("HistoryToolbar_ClearHistoryMessage", Culture)!;

    public static string HistoryToolbar_ClearButton =>
        ResourceManager.GetString("HistoryToolbar_ClearButton", Culture)!;

    public static string HistoryToolbar_CancelButton =>
        ResourceManager.GetString("HistoryToolbar_CancelButton", Culture)!;

    public static string HistoryToolbar_ExportTitle =>
        ResourceManager.GetString("HistoryToolbar_ExportTitle", Culture)!;

    // Playback
    public static string Playback_RestartTrack =>
        ResourceManager.GetString("Playback_RestartTrack", Culture)!;

    public static string Playback_Delay =>
        ResourceManager.GetString("Playback_Delay", Culture)!;

    public static string Playback_Stop =>
        ResourceManager.GetString("Playback_Stop", Culture)!;

    public static string Playback_RestartTitle =>
        ResourceManager.GetString("Playback_RestartTitle", Culture)!;

    public static string Playback_RestartMessage =>
        ResourceManager.GetString("Playback_RestartMessage", Culture)!;

    public static string Playback_RestartButton =>
        ResourceManager.GetString("Playback_RestartButton", Culture)!;

    public static string Playback_CancelButton =>
        ResourceManager.GetString("Playback_CancelButton", Culture)!;

    public static string Playback_SkipTitle =>
        ResourceManager.GetString("Playback_SkipTitle", Culture)!;

    public static string Playback_SkipMessage =>
        ResourceManager.GetString("Playback_SkipMessage", Culture)!;

    public static string Playback_SkipButton =>
        ResourceManager.GetString("Playback_SkipButton", Culture)!;

    public static string Playback_ClearTitle =>
        ResourceManager.GetString("Playback_ClearTitle", Culture)!;

    public static string Playback_ClearMessage =>
        ResourceManager.GetString("Playback_ClearMessage", Culture)!;

    public static string Playback_ClearButton =>
        ResourceManager.GetString("Playback_ClearButton", Culture)!;

    public static string Playback_SeekTitle =>
        ResourceManager.GetString("Playback_SeekTitle", Culture)!;

    public static string Playback_SeekMessage =>
        ResourceManager.GetString("Playback_SeekMessage", Culture)!;

    public static string Playback_SeekButton =>
        ResourceManager.GetString("Playback_SeekButton", Culture)!;

    public static string Playback_AudioUnavailable =>
        ResourceManager.GetString("Playback_AudioUnavailable", Culture)!;

    // Track Catalog
    public static string TrackCatalog_ColumnDance =>
        ResourceManager.GetString("TrackCatalog_ColumnDance", Culture)!;

    public static string TrackCatalog_ColumnArtist =>
        ResourceManager.GetString("TrackCatalog_ColumnArtist", Culture)!;

    public static string TrackCatalog_ColumnTitle =>
        ResourceManager.GetString("TrackCatalog_ColumnTitle", Culture)!;

    public static string TrackCatalog_ColumnLength =>
        ResourceManager.GetString("TrackCatalog_ColumnLength", Culture)!;

    public static string TrackCatalog_SearchWatermark =>
        ResourceManager.GetString("TrackCatalog_SearchWatermark", Culture)!;

    public static string TrackCatalog_ClearSearch =>
        ResourceManager.GetString("TrackCatalog_ClearSearch", Culture)!;

    // Dance Tree
    // Dance Tree Toolbar
    // Dance Synonyms
    // Presentation
    public static string Presentation_WindowTitle =>
        ResourceManager.GetString("Presentation_WindowTitle", Culture)!;

    public static string Presentation_NoTrackPlaying =>
        ResourceManager.GetString("Presentation_NoTrackPlaying", Culture)!;

    public static string Presentation_Next =>
        ResourceManager.GetString("Presentation_Next", Culture)!;

    public static string Presentation_NoNextTrack =>
        ResourceManager.GetString("Presentation_NoNextTrack", Culture)!;

    public static string Presentation_Delay =>
        ResourceManager.GetString("Presentation_Delay", Culture)!;

    public static string Presentation_Stop =>
        ResourceManager.GetString("Presentation_Stop", Culture)!;

    public static string Presentation_Message =>
        ResourceManager.GetString("Presentation_Message", Culture)!;

    // Dialogs
    public static string Dialog_RequestMessageTitle =>
        ResourceManager.GetString("Dialog_RequestMessageTitle", Culture)!;

    public static string Dialog_MessageLabel =>
        ResourceManager.GetString("Dialog_MessageLabel", Culture)!;

    public static string Dialog_MessageWatermark =>
        ResourceManager.GetString("Dialog_MessageWatermark", Culture)!;

    public static string Dialog_UseTimedDelay =>
        ResourceManager.GetString("Dialog_UseTimedDelay", Culture)!;

    public static string Dialog_DelayDuration =>
        ResourceManager.GetString("Dialog_DelayDuration", Culture)!;

    public static string Dialog_Cancel =>
        ResourceManager.GetString("Dialog_Cancel", Culture)!;

    public static string Dialog_OK =>
        ResourceManager.GetString("Dialog_OK", Culture)!;

    public static string Dialog_ConfirmDefault =>
        ResourceManager.GetString("Dialog_ConfirmDefault", Culture)!;

    public static string Dialog_YesDefault =>
        ResourceManager.GetString("Dialog_YesDefault", Culture)!;

    public static string Dialog_NoDefault =>
        ResourceManager.GetString("Dialog_NoDefault", Culture)!;

    public static string Dialog_AreYouSure =>
        ResourceManager.GetString("Dialog_AreYouSure", Culture)!;

    public static string Dialog_CharacterCountFormat =>
        ResourceManager.GetString("Dialog_CharacterCountFormat", Culture)!;

    // App
    public static string App_ExitTitle =>
        ResourceManager.GetString("App_ExitTitle", Culture)!;

    public static string App_ExitMessage =>
        ResourceManager.GetString("App_ExitMessage", Culture)!;

    public static string Settings_LanguageRestartTitle =>
        ResourceManager.GetString("Settings_LanguageRestartTitle", Culture)!;

    public static string Settings_LanguageRestartMessage =>
        ResourceManager.GetString("Settings_LanguageRestartMessage", Culture)!;

    public static string Dialog_Restart =>
        ResourceManager.GetString("Dialog_Restart", Culture)!;

    public static string Equalizer_Title =>
        ResourceManager.GetString("Equalizer_Title", Culture)!;

    public static string Equalizer_On =>
        ResourceManager.GetString("Equalizer_On", Culture)!;

    public static string Equalizer_Off =>
        ResourceManager.GetString("Equalizer_Off", Culture)!;

    public static string Equalizer_Enable =>
        ResourceManager.GetString("Equalizer_Enable", Culture)!;

    public static string Equalizer_LowCut =>
        ResourceManager.GetString("Equalizer_LowCut", Culture)!;

    public static string Equalizer_Preamp =>
        ResourceManager.GetString("Equalizer_Preamp", Culture)!;

    public static string Equalizer_Reset =>
        ResourceManager.GetString("Equalizer_Reset", Culture)!;

    public static string Equalizer_Unavailable =>
        ResourceManager.GetString("Equalizer_Unavailable", Culture)!;

    public static string Settings_WebServerSection =>
        ResourceManager.GetString("Settings_WebServerSection", Culture)!;

    public static string Settings_WebServerEnabled =>
        ResourceManager.GetString("Settings_WebServerEnabled", Culture)!;

    public static string Settings_WebServerDescription =>
        ResourceManager.GetString("Settings_WebServerDescription", Culture)!;

    public static string Settings_WebServerPort =>
        ResourceManager.GetString("Settings_WebServerPort", Culture)!;

    public static string Settings_WebRemoteControlEnabled =>
        ResourceManager.GetString("Settings_WebRemoteControlEnabled", Culture)!;

    public static string Settings_WebRemoteControlDescription =>
        ResourceManager.GetString("Settings_WebRemoteControlDescription", Culture)!;

    public static string Settings_WebRemoteControlPin =>
        ResourceManager.GetString("Settings_WebRemoteControlPin", Culture)!;

    public static string Settings_WebRegeneratePin =>
        ResourceManager.GetString("Settings_WebRegeneratePin", Culture)!;

    public static string Settings_WebRegeneratePinDescription =>
        ResourceManager.GetString("Settings_WebRegeneratePinDescription", Culture)!;

    public static string Settings_WebServerAddresses =>
        ResourceManager.GetString("Settings_WebServerAddresses", Culture)!;

    public static string Settings_WebServerRunning =>
        ResourceManager.GetString("Settings_WebServerRunning", Culture)!;

    public static string Settings_WebServerStopped =>
        ResourceManager.GetString("Settings_WebServerStopped", Culture)!;

    public static string Settings_WebServerStarting =>
        ResourceManager.GetString("Settings_WebServerStarting", Culture)!;

    public static string Settings_WebServerFailed =>
        ResourceManager.GetString("Settings_WebServerFailed", Culture)!;

    public static string Settings_WebServerStopping =>
        ResourceManager.GetString("Settings_WebServerStopping", Culture)!;

    // Setup wizard
    public static string Wizard_Title =>
        ResourceManager.GetString("Wizard_Title", Culture)!;

    public static string Wizard_StepFormat =>
        ResourceManager.GetString("Wizard_StepFormat", Culture)!;

    public static string Wizard_Back =>
        ResourceManager.GetString("Wizard_Back", Culture)!;

    public static string Wizard_Next =>
        ResourceManager.GetString("Wizard_Next", Culture)!;

    public static string Wizard_Finish =>
        ResourceManager.GetString("Wizard_Finish", Culture)!;

    public static string Wizard_DanceList_Title =>
        ResourceManager.GetString("Wizard_DanceList_Title", Culture)!;

    public static string Wizard_DanceList_Explanation =>
        ResourceManager.GetString("Wizard_DanceList_Explanation", Culture)!;

    public static string Wizard_DanceList_Source =>
        ResourceManager.GetString("Wizard_DanceList_Source", Culture)!;

    public static string Wizard_Music_Title =>
        ResourceManager.GetString("Wizard_Music_Title", Culture)!;

    public static string Wizard_Music_Explanation =>
        ResourceManager.GetString("Wizard_Music_Explanation", Culture)!;

    public static string Wizard_Music_Note =>
        ResourceManager.GetString("Wizard_Music_Note", Culture)!;

    public static string Settings_RunSetupAgain =>
        ResourceManager.GetString("Settings_RunSetupAgain", Culture)!;

    public static string Settings_RunSetupAgainDescription =>
        ResourceManager.GetString("Settings_RunSetupAgainDescription", Culture)!;

    // Dance panel
    public static string Wizard_DanceList_Summary =>
        ResourceManager.GetString("Wizard_DanceList_Summary", Culture)!;

    public static string Wizard_DanceList_Detail =>
        ResourceManager.GetString("Wizard_DanceList_Detail", Culture)!;

    public static string DanceList_SearchWatermark =>
        ResourceManager.GetString("DanceList_SearchWatermark", Culture)!;

    public static string DanceList_TagsHeader =>
        ResourceManager.GetString("DanceList_TagsHeader", Culture)!;

    public static string DanceList_PoolEverything =>
        ResourceManager.GetString("DanceList_PoolEverything", Culture)!;

    public static string DanceList_PoolFormat =>
        ResourceManager.GetString("DanceList_PoolFormat", Culture)!;

    public static string DanceList_ClearPool =>
        ResourceManager.GetString("DanceList_ClearPool", Culture)!;

    public static string DanceList_ClearPoolTip =>
        ResourceManager.GetString("DanceList_ClearPoolTip", Culture)!;

    public static string DanceList_Summary =>
        ResourceManager.GetString("DanceList_Summary", Culture)!;

    public static string DanceList_Obtained =>
        ResourceManager.GetString("DanceList_Obtained", Culture)!;

    public static string DanceList_ObtainedBuiltIn =>
        ResourceManager.GetString("DanceList_ObtainedBuiltIn", Culture)!;

    public static string DanceList_Update =>
        ResourceManager.GetString("DanceList_Update", Culture)!;

    public static string DanceList_UpdateTip =>
        ResourceManager.GetString("DanceList_UpdateTip", Culture)!;

    public static string DanceList_UpdateFromFile =>
        ResourceManager.GetString("DanceList_UpdateFromFile", Culture)!;

    public static string DanceList_UpdateFromFileTip =>
        ResourceManager.GetString("DanceList_UpdateFromFileTip", Culture)!;

    public static string DanceList_Updated =>
        ResourceManager.GetString("DanceList_Updated", Culture)!;

    public static string DanceList_AlreadyCurrent =>
        ResourceManager.GetString("DanceList_AlreadyCurrent", Culture)!;

    public static string DanceList_UpdateFailed =>
        ResourceManager.GetString("DanceList_UpdateFailed", Culture)!;

    public static string DanceList_TrackCount =>
        ResourceManager.GetString("DanceList_TrackCount", Culture)!;

    public static string DanceList_NoTracks =>
        ResourceManager.GetString("DanceList_NoTracks", Culture)!;

    public static string DanceList_PickThisDance =>
        ResourceManager.GetString("DanceList_PickThisDance", Culture)!;

    public static string DanceList_NoTrackForDance =>
        ResourceManager.GetString("DanceList_NoTrackForDance", Culture)!;

    public static string Wizard_DanceList_SourceUrl =>
        ResourceManager.GetString("Wizard_DanceList_SourceUrl", Culture)!;

    public static string DanceList_Title =>
        ResourceManager.GetString("DanceList_Title", Culture)!;

    // Setup wizard: emptying the list
    // Dance list scope
    public static string DanceListToolbar_SwitchToTrackList =>
        ResourceManager.GetString("DanceListToolbar_SwitchToTrackList", Culture)!;

    public static string DanceListToolbar_TrackListLabel =>
        ResourceManager.GetString("DanceListToolbar_TrackListLabel", Culture)!;

    public static string TrackCatalog_SwitchToDanceList =>
        ResourceManager.GetString("TrackCatalog_SwitchToDanceList", Culture)!;

    public static string TrackCatalog_DancesLabel =>
        ResourceManager.GetString("TrackCatalog_DancesLabel", Culture)!;

    // Tagging editor
    public static string Tagging_Title =>
        ResourceManager.GetString("Tagging_Title", Culture)!;

    public static string Toolbar_Tagging =>
        ResourceManager.GetString("Toolbar_Tagging", Culture)!;

    public static string Toolbar_TaggingLabel =>
        ResourceManager.GetString("Toolbar_TaggingLabel", Culture)!;

    public static string Tagging_Summary =>
        ResourceManager.GetString("Tagging_Summary", Culture)!;

    public static string Tagging_NothingToDo =>
        ResourceManager.GetString("Tagging_NothingToDo", Culture)!;

    public static string Tagging_TrackCount =>
        ResourceManager.GetString("Tagging_TrackCount", Culture)!;

    public static string Tagging_MapTo =>
        ResourceManager.GetString("Tagging_MapTo", Culture)!;

    public static string Tagging_MapFolder =>
        ResourceManager.GetString("Tagging_MapFolder", Culture)!;

    public static string Tagging_MapTrack =>
        ResourceManager.GetString("Tagging_MapTrack", Culture)!;

    public static string Tagging_Ignore =>
        ResourceManager.GetString("Tagging_Ignore", Culture)!;

    public static string Tagging_IgnoreTooltip =>
        ResourceManager.GetString("Tagging_IgnoreTooltip", Culture)!;

    public static string Tagging_Ignored =>
        ResourceManager.GetString("Tagging_Ignored", Culture)!;

    public static string Tagging_ShowTracks =>
        ResourceManager.GetString("Tagging_ShowTracks", Culture)!;

    public static string Tagging_Preview =>
        ResourceManager.GetString("Tagging_Preview", Culture)!;

    public static string Tagging_StopPreview =>
        ResourceManager.GetString("Tagging_StopPreview", Culture)!;

    public static string Tagging_PreviewRefused =>
        ResourceManager.GetString("Tagging_PreviewRefused", Culture)!;

    public static string Tagging_SuggestionWithCount =>
        ResourceManager.GetString("Tagging_SuggestionWithCount", Culture)!;

    public static string Tagging_LooksLikeAMisspelling =>
        ResourceManager.GetString("Tagging_LooksLikeAMisspelling", Culture)!;

    public static string Tagging_TooGeneralExplanation =>
        ResourceManager.GetString("Tagging_TooGeneralExplanation", Culture)!;

    public static string Tagging_NothingLooksLikeIt =>
        ResourceManager.GetString("Tagging_NothingLooksLikeIt", Culture)!;

    public static string Tagging_FolderAgrees =>
        ResourceManager.GetString("Tagging_FolderAgrees", Culture)!;

    public static string Tagging_FolderSaysNothing =>
        ResourceManager.GetString("Tagging_FolderSaysNothing", Culture)!;

    public static string Tagging_BucketSuggestions =>
        ResourceManager.GetString("Tagging_BucketSuggestions", Culture)!;

    public static string Tagging_BucketSuggestionsHint =>
        ResourceManager.GetString("Tagging_BucketSuggestionsHint", Culture)!;

    public static string Tagging_BucketUnrecognised =>
        ResourceManager.GetString("Tagging_BucketUnrecognised", Culture)!;

    public static string Tagging_BucketUnrecognisedHint =>
        ResourceManager.GetString("Tagging_BucketUnrecognisedHint", Culture)!;

    public static string Tagging_BucketOneOffs =>
        ResourceManager.GetString("Tagging_BucketOneOffs", Culture)!;

    public static string Tagging_BucketOneOffsHint =>
        ResourceManager.GetString("Tagging_BucketOneOffsHint", Culture)!;

    public static string Wizard_Tagging_Title =>
        ResourceManager.GetString("Wizard_Tagging_Title", Culture)!;

    public static string Wizard_Tagging_Explanation =>
        ResourceManager.GetString("Wizard_Tagging_Explanation", Culture)!;

    public static string Toolbar_TaggingCount =>
        ResourceManager.GetString("Toolbar_TaggingCount", Culture)!;

    public static string Tagging_StillReading =>
        ResourceManager.GetString("Tagging_StillReading", Culture)!;

    public static string Tagging_AmbiguousExplanation =>
        ResourceManager.GetString("Tagging_AmbiguousExplanation", Culture)!;

    public static string Tagging_ScanProgress =>
        ResourceManager.GetString("Tagging_ScanProgress", Culture)!;

    public static string Tagging_SearchDances =>
        ResourceManager.GetString("Tagging_SearchDances", Culture)!;

    public static string Tagging_DecidedAs =>
        ResourceManager.GetString("Tagging_DecidedAs", Culture)!;

    public static string Tagging_DecidedNotADance =>
        ResourceManager.GetString("Tagging_DecidedNotADance", Culture)!;

    // Setup: welcome
    public static string Wizard_Welcome_Title =>
        ResourceManager.GetString("Wizard_Welcome_Title", Culture)!;

    public static string Wizard_Welcome_Explanation =>
        ResourceManager.GetString("Wizard_Welcome_Explanation", Culture)!;

    public static string Wizard_Welcome_Stage1 =>
        ResourceManager.GetString("Wizard_Welcome_Stage1", Culture)!;

    public static string Wizard_Welcome_Stage1Detail =>
        ResourceManager.GetString("Wizard_Welcome_Stage1Detail", Culture)!;

    public static string Wizard_Welcome_Stage2 =>
        ResourceManager.GetString("Wizard_Welcome_Stage2", Culture)!;

    public static string Wizard_Welcome_Stage2Detail =>
        ResourceManager.GetString("Wizard_Welcome_Stage2Detail", Culture)!;

    public static string Wizard_Welcome_Stage3 =>
        ResourceManager.GetString("Wizard_Welcome_Stage3", Culture)!;

    public static string Wizard_Welcome_Stage3Detail =>
        ResourceManager.GetString("Wizard_Welcome_Stage3Detail", Culture)!;

    public static string Wizard_Welcome_Source =>
        ResourceManager.GetString("Wizard_Welcome_Source", Culture)!;

    public static string Wizard_Music_Required =>
        ResourceManager.GetString("Wizard_Music_Required", Culture)!;

    public static string Settings_MusicDirectoryChangeHint =>
        ResourceManager.GetString("Settings_MusicDirectoryChangeHint", Culture)!;

    // Advanced discovery
    public static string Settings_AdvancedDiscovery =>
        ResourceManager.GetString("Settings_AdvancedDiscovery", Culture)!;

    public static string Settings_AdvancedDiscoveryHint =>
        ResourceManager.GetString("Settings_AdvancedDiscoveryHint", Culture)!;

    public static string Discovery_Title =>
        ResourceManager.GetString("Discovery_Title", Culture)!;

    public static string Discovery_Intro =>
        ResourceManager.GetString("Discovery_Intro", Culture)!;

    public static string Discovery_PatternsHeader =>
        ResourceManager.GetString("Discovery_PatternsHeader", Culture)!;

    public static string Discovery_PatternsHint =>
        ResourceManager.GetString("Discovery_PatternsHint", Culture)!;

    public static string Discovery_DraftWatermark =>
        ResourceManager.GetString("Discovery_DraftWatermark", Culture)!;

    public static string Discovery_Declare =>
        ResourceManager.GetString("Discovery_Declare", Culture)!;

    public static string Discovery_PatternMatches =>
        ResourceManager.GetString("Discovery_PatternMatches", Culture)!;

    public static string Discovery_Coverage =>
        ResourceManager.GetString("Discovery_Coverage", Culture)!;

    public static string Discovery_SamplesHeader =>
        ResourceManager.GetString("Discovery_SamplesHeader", Culture)!;

    public static string Discovery_MissesHeader =>
        ResourceManager.GetString("Discovery_MissesHeader", Culture)!;

    public static string Discovery_ShowDetails =>
        ResourceManager.GetString("Discovery_ShowDetails", Culture)!;

    public static string Discovery_Remove =>
        ResourceManager.GetString("Discovery_Remove", Culture)!;

    public static string Discovery_MoveUp =>
        ResourceManager.GetString("Discovery_MoveUp", Culture)!;

    public static string Discovery_MoveDown =>
        ResourceManager.GetString("Discovery_MoveDown", Culture)!;

    public static string Discovery_ProblemUnknownToken =>
        ResourceManager.GetString("Discovery_ProblemUnknownToken", Culture)!;

    public static string Discovery_ProblemNoFields =>
        ResourceManager.GetString("Discovery_ProblemNoFields", Culture)!;

    public static string Discovery_ProblemAdjacentFields =>
        ResourceManager.GetString("Discovery_ProblemAdjacentFields", Culture)!;

    public static string Discovery_ProblemDuplicateField =>
        ResourceManager.GetString("Discovery_ProblemDuplicateField", Culture)!;

    public static string Discovery_FoldersHeader =>
        ResourceManager.GetString("Discovery_FoldersHeader", Culture)!;

    public static string Discovery_FoldersHint =>
        ResourceManager.GetString("Discovery_FoldersHint", Culture)!;

    public static string Discovery_LevelLabel =>
        ResourceManager.GetString("Discovery_LevelLabel", Culture)!;

    public static string Discovery_LevelDepth =>
        ResourceManager.GetString("Discovery_LevelDepth", Culture)!;

    public static string Discovery_LevelValue =>
        ResourceManager.GetString("Discovery_LevelValue", Culture)!;

    public static string Discovery_TagsHeader =>
        ResourceManager.GetString("Discovery_TagsHeader", Culture)!;

    public static string Discovery_TagsHint =>
        ResourceManager.GetString("Discovery_TagsHint", Culture)!;

    public static string Discovery_UseDefault =>
        ResourceManager.GetString("Discovery_UseDefault", Culture)!;

    public static string Discovery_ApplyRolesAndTags =>
        ResourceManager.GetString("Discovery_ApplyRolesAndTags", Culture)!;

    public static string Discovery_FieldDance =>
        ResourceManager.GetString("Discovery_FieldDance", Culture)!;

    public static string Discovery_FieldArtist =>
        ResourceManager.GetString("Discovery_FieldArtist", Culture)!;

    public static string Discovery_FieldTitle =>
        ResourceManager.GetString("Discovery_FieldTitle", Culture)!;

    public static string Discovery_TagTitle =>
        ResourceManager.GetString("Discovery_TagTitle", Culture)!;

    public static string Discovery_TagArtist =>
        ResourceManager.GetString("Discovery_TagArtist", Culture)!;

    public static string Discovery_TagAlbumArtist =>
        ResourceManager.GetString("Discovery_TagAlbumArtist", Culture)!;

    public static string Discovery_TagAlbum =>
        ResourceManager.GetString("Discovery_TagAlbum", Culture)!;

    public static string Discovery_TagComment =>
        ResourceManager.GetString("Discovery_TagComment", Culture)!;

    public static string Discovery_RoleUnknown =>
        ResourceManager.GetString("Discovery_RoleUnknown", Culture)!;

    public static string Discovery_RoleArtist =>
        ResourceManager.GetString("Discovery_RoleArtist", Culture)!;

    public static string Discovery_RoleAlbum =>
        ResourceManager.GetString("Discovery_RoleAlbum", Culture)!;

    public static string Discovery_RoleDance =>
        ResourceManager.GetString("Discovery_RoleDance", Culture)!;

    public static string Discovery_RoleIgnore =>
        ResourceManager.GetString("Discovery_RoleIgnore", Culture)!;

    public static string Discovery_NoLibrary =>
        ResourceManager.GetString("Discovery_NoLibrary", Culture)!;

    // Review
    public static string Review_Title =>
        ResourceManager.GetString("Review_Title", Culture)!;

    public static string Review_Intro =>
        ResourceManager.GetString("Review_Intro", Culture)!;

    public static string Review_Keys =>
        ResourceManager.GetString("Review_Keys", Culture)!;

    public static string Review_Waiting =>
        ResourceManager.GetString("Review_Waiting", Culture)!;

    public static string Review_NothingWaiting =>
        ResourceManager.GetString("Review_NothingWaiting", Culture)!;

    public static string Review_Approve =>
        ResourceManager.GetString("Review_Approve", Culture)!;

    public static string Review_ApproveFolder =>
        ResourceManager.GetString("Review_ApproveFolder", Culture)!;

    public static string Review_Dance =>
        ResourceManager.GetString("Review_Dance", Culture)!;

    public static string Review_Artist =>
        ResourceManager.GetString("Review_Artist", Culture)!;

    public static string Review_TitleField =>
        ResourceManager.GetString("Review_TitleField", Culture)!;

    public static string Review_RootFolder =>
        ResourceManager.GetString("Review_RootFolder", Culture)!;

    public static string Review_FromTag =>
        ResourceManager.GetString("Review_FromTag", Culture)!;

    public static string Review_FromFileName =>
        ResourceManager.GetString("Review_FromFileName", Culture)!;

    public static string Review_FromFolder =>
        ResourceManager.GetString("Review_FromFolder", Culture)!;

    public static string Review_FromRule =>
        ResourceManager.GetString("Review_FromRule", Culture)!;

    public static string Review_FromYou =>
        ResourceManager.GetString("Review_FromYou", Culture)!;

    public static string Review_FromNothing =>
        ResourceManager.GetString("Review_FromNothing", Culture)!;

    public static string Review_ReasonMissing =>
        ResourceManager.GetString("Review_ReasonMissing", Culture)!;

    public static string Review_ReasonUnapproved =>
        ResourceManager.GetString("Review_ReasonUnapproved", Culture)!;

    public static string Review_ReasonUnknownDance =>
        ResourceManager.GetString("Review_ReasonUnknownDance", Culture)!;

    public static string Review_ReasonChanged =>
        ResourceManager.GetString("Review_ReasonChanged", Culture)!;

    public static string Review_Answered =>
        ResourceManager.GetString("Review_Answered", Culture)!;

    public static string Review_ParkedOnUnknownDance =>
        ResourceManager.GetString("Review_ParkedOnUnknownDance", Culture)!;

    public static string Review_UnknownDanceHint =>
        ResourceManager.GetString("Review_UnknownDanceHint", Culture)!;

    public static string Toolbar_Review =>
        ResourceManager.GetString("Toolbar_Review", Culture)!;

    public static string Toolbar_ReviewLabel =>
        ResourceManager.GetString("Toolbar_ReviewLabel", Culture)!;

    public static string Toolbar_ReviewCount =>
        ResourceManager.GetString("Toolbar_ReviewCount", Culture)!;
}
