//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Ready4Balfolk.UI.Resources;

using System.Globalization;
using System.Resources;

public static class UiStrings
{
    private static ResourceManager? _resourceManager;

    public static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager(
            "Ready4Balfolk.UI.Resources.UiStrings",
            typeof(UiStrings).Assembly);

    public static CultureInfo? Culture { get; set; }

    // MainWindow
    public static string MainWindow_Title =>
        ResourceManager.GetString("MainWindow_Title", Culture)!;

    public static string MainWindow_Back =>
        ResourceManager.GetString("MainWindow_Back", Culture)!;

    public static string MainWindow_Settings =>
        ResourceManager.GetString("MainWindow_Settings", Culture)!;

    public static string MainWindow_Help =>
        ResourceManager.GetString("MainWindow_Help", Culture)!;

    // Toolbar
    public static string Toolbar_Exit =>
        ResourceManager.GetString("Toolbar_Exit", Culture)!;

    public static string Toolbar_Help =>
        ResourceManager.GetString("Toolbar_Help", Culture)!;

    public static string Toolbar_Settings =>
        ResourceManager.GetString("Toolbar_Settings", Culture)!;

    public static string Toolbar_DanceSynonyms =>
        ResourceManager.GetString("Toolbar_DanceSynonyms", Culture)!;

    // Settings
    public static string Settings_Title =>
        ResourceManager.GetString("Settings_Title", Culture)!;

    public static string Settings_MusicDirectory =>
        ResourceManager.GetString("Settings_MusicDirectory", Culture)!;

    public static string Settings_MusicDirectoryWatermark =>
        ResourceManager.GetString("Settings_MusicDirectoryWatermark", Culture)!;

    public static string Settings_Browse =>
        ResourceManager.GetString("Settings_Browse", Culture)!;

    public static string Settings_MaxQueueItems =>
        ResourceManager.GetString("Settings_MaxQueueItems", Culture)!;

    public static string Settings_DelayDuration =>
        ResourceManager.GetString("Settings_DelayDuration", Culture)!;

    public static string Settings_DelayDescription =>
        ResourceManager.GetString("Settings_DelayDescription", Culture)!;

    public static string Settings_PresentationDisplays =>
        ResourceManager.GetString("Settings_PresentationDisplays", Culture)!;

    public static string Settings_PresentationDescription =>
        ResourceManager.GetString("Settings_PresentationDescription", Culture)!;

    public static string Settings_AutoQueue =>
        ResourceManager.GetString("Settings_AutoQueue", Culture)!;

    public static string Settings_AutoQueueDescription =>
        ResourceManager.GetString("Settings_AutoQueueDescription", Culture)!;

    public static string Settings_AllowDuplicates =>
        ResourceManager.GetString("Settings_AllowDuplicates", Culture)!;

    public static string Settings_AllowDuplicatesDescription =>
        ResourceManager.GetString("Settings_AllowDuplicatesDescription", Culture)!;

    public static string Settings_ConfirmPlayback =>
        ResourceManager.GetString("Settings_ConfirmPlayback", Culture)!;

    public static string Settings_ConfirmPlaybackDescription =>
        ResourceManager.GetString("Settings_ConfirmPlaybackDescription", Culture)!;

    public static string Settings_Theme =>
        ResourceManager.GetString("Settings_Theme", Culture)!;

    public static string Settings_ThemeDescription =>
        ResourceManager.GetString("Settings_ThemeDescription", Culture)!;

    public static string Settings_Language =>
        ResourceManager.GetString("Settings_Language", Culture)!;

    public static string Settings_LanguageDescription =>
        ResourceManager.GetString("Settings_LanguageDescription", Culture)!;

    public static string Settings_Troubleshooting =>
        ResourceManager.GetString("Settings_Troubleshooting", Culture)!;

    public static string Settings_ExportLog =>
        ResourceManager.GetString("Settings_ExportLog", Culture)!;

    public static string Settings_ExportLogDescription =>
        ResourceManager.GetString("Settings_ExportLogDescription", Culture)!;

    public static string Settings_VersionFormat =>
        ResourceManager.GetString("Settings_VersionFormat", Culture)!;

    public static string Settings_SelectMusicDirectory =>
        ResourceManager.GetString("Settings_SelectMusicDirectory", Culture)!;

    public static string Settings_ExportLogTitle =>
        ResourceManager.GetString("Settings_ExportLogTitle", Culture)!;

    // Queue
    public static string Queue_StopMarker =>
        ResourceManager.GetString("Queue_StopMarker", Culture)!;

    public static string Queue_DelayMarker =>
        ResourceManager.GetString("Queue_DelayMarker", Culture)!;

    public static string Queue_MessageMarker =>
        ResourceManager.GetString("Queue_MessageMarker", Culture)!;

    public static string Queue_RefreshAutoTrack =>
        ResourceManager.GetString("Queue_RefreshAutoTrack", Culture)!;

    public static string Queue_KeepTrack =>
        ResourceManager.GetString("Queue_KeepTrack", Culture)!;

    public static string Queue_Empty =>
        ResourceManager.GetString("Queue_Empty", Culture)!;

    public static string Queue_ItemCount =>
        ResourceManager.GetString("Queue_ItemCount", Culture)!;

    public static string Queue_ItemCountPlural =>
        ResourceManager.GetString("Queue_ItemCountPlural", Culture)!;

    public static string Queue_PlaylistFinishesAt =>
        ResourceManager.GetString("Queue_PlaylistFinishesAt", Culture)!;

    public static string Queue_PlaylistHaltsAt =>
        ResourceManager.GetString("Queue_PlaylistHaltsAt", Culture)!;

    // Queue Toolbar
    public static string QueueToolbar_SwitchToHistory =>
        ResourceManager.GetString("QueueToolbar_SwitchToHistory", Culture)!;

    public static string QueueToolbar_QueueRandomTrack =>
        ResourceManager.GetString("QueueToolbar_QueueRandomTrack", Culture)!;

    public static string QueueToolbar_RequestStop =>
        ResourceManager.GetString("QueueToolbar_RequestStop", Culture)!;

    public static string QueueToolbar_RequestDelay =>
        ResourceManager.GetString("QueueToolbar_RequestDelay", Culture)!;

    public static string QueueToolbar_RequestMessage =>
        ResourceManager.GetString("QueueToolbar_RequestMessage", Culture)!;

    public static string QueueToolbar_RemoveSelected =>
        ResourceManager.GetString("QueueToolbar_RemoveSelected", Culture)!;

    public static string QueueToolbar_ClearQueue =>
        ResourceManager.GetString("QueueToolbar_ClearQueue", Culture)!;

    public static string QueueToolbar_ClearQueueTitle =>
        ResourceManager.GetString("QueueToolbar_ClearQueueTitle", Culture)!;

    public static string QueueToolbar_ClearQueueMessage =>
        ResourceManager.GetString("QueueToolbar_ClearQueueMessage", Culture)!;

    public static string QueueToolbar_ClearButton =>
        ResourceManager.GetString("QueueToolbar_ClearButton", Culture)!;

    public static string QueueToolbar_CancelButton =>
        ResourceManager.GetString("QueueToolbar_CancelButton", Culture)!;

    // History
    public static string History_NoHistory =>
        ResourceManager.GetString("History_NoHistory", Culture)!;

    public static string History_ItemCount =>
        ResourceManager.GetString("History_ItemCount", Culture)!;

    public static string History_ItemCountPlural =>
        ResourceManager.GetString("History_ItemCountPlural", Culture)!;

    public static string History_TypeTrack =>
        ResourceManager.GetString("History_TypeTrack", Culture)!;

    public static string History_TypeMessage =>
        ResourceManager.GetString("History_TypeMessage", Culture)!;

    public static string History_TypeDelay =>
        ResourceManager.GetString("History_TypeDelay", Culture)!;

    public static string History_TypeStop =>
        ResourceManager.GetString("History_TypeStop", Culture)!;

    public static string History_StatusFinished =>
        ResourceManager.GetString("History_StatusFinished", Culture)!;

    public static string History_StatusSkipped =>
        ResourceManager.GetString("History_StatusSkipped", Culture)!;

    // History Toolbar
    public static string HistoryToolbar_SwitchToQueue =>
        ResourceManager.GetString("HistoryToolbar_SwitchToQueue", Culture)!;

    public static string HistoryToolbar_ExportHistory =>
        ResourceManager.GetString("HistoryToolbar_ExportHistory", Culture)!;

    public static string HistoryToolbar_ClearHistory =>
        ResourceManager.GetString("HistoryToolbar_ClearHistory", Culture)!;

    public static string HistoryToolbar_ClearHistoryTitle =>
        ResourceManager.GetString("HistoryToolbar_ClearHistoryTitle", Culture)!;

    public static string HistoryToolbar_ClearHistoryMessage =>
        ResourceManager.GetString("HistoryToolbar_ClearHistoryMessage", Culture)!;

    public static string HistoryToolbar_ClearButton =>
        ResourceManager.GetString("HistoryToolbar_ClearButton", Culture)!;

    public static string HistoryToolbar_CancelButton =>
        ResourceManager.GetString("HistoryToolbar_CancelButton", Culture)!;

    public static string HistoryToolbar_ExportTitle =>
        ResourceManager.GetString("HistoryToolbar_ExportTitle", Culture)!;

    // Playback
    public static string Playback_RestartTrack =>
        ResourceManager.GetString("Playback_RestartTrack", Culture)!;

    public static string Playback_Delay =>
        ResourceManager.GetString("Playback_Delay", Culture)!;

    public static string Playback_Stop =>
        ResourceManager.GetString("Playback_Stop", Culture)!;

    public static string Playback_RestartTitle =>
        ResourceManager.GetString("Playback_RestartTitle", Culture)!;

    public static string Playback_RestartMessage =>
        ResourceManager.GetString("Playback_RestartMessage", Culture)!;

    public static string Playback_RestartButton =>
        ResourceManager.GetString("Playback_RestartButton", Culture)!;

    public static string Playback_CancelButton =>
        ResourceManager.GetString("Playback_CancelButton", Culture)!;

    public static string Playback_SkipTitle =>
        ResourceManager.GetString("Playback_SkipTitle", Culture)!;

    public static string Playback_SkipMessage =>
        ResourceManager.GetString("Playback_SkipMessage", Culture)!;

    public static string Playback_SkipButton =>
        ResourceManager.GetString("Playback_SkipButton", Culture)!;

    public static string Playback_ClearTitle =>
        ResourceManager.GetString("Playback_ClearTitle", Culture)!;

    public static string Playback_ClearMessage =>
        ResourceManager.GetString("Playback_ClearMessage", Culture)!;

    public static string Playback_ClearButton =>
        ResourceManager.GetString("Playback_ClearButton", Culture)!;

    public static string Playback_AudioUnavailable =>
        ResourceManager.GetString("Playback_AudioUnavailable", Culture)!;

    // Track Catalog
    public static string TrackCatalog_ColumnDance =>
        ResourceManager.GetString("TrackCatalog_ColumnDance", Culture)!;

    public static string TrackCatalog_ColumnArtist =>
        ResourceManager.GetString("TrackCatalog_ColumnArtist", Culture)!;

    public static string TrackCatalog_ColumnTitle =>
        ResourceManager.GetString("TrackCatalog_ColumnTitle", Culture)!;

    public static string TrackCatalog_ColumnLength =>
        ResourceManager.GetString("TrackCatalog_ColumnLength", Culture)!;

    public static string TrackCatalog_SwitchToDanceTree =>
        ResourceManager.GetString("TrackCatalog_SwitchToDanceTree", Culture)!;

    public static string TrackCatalog_SearchWatermark =>
        ResourceManager.GetString("TrackCatalog_SearchWatermark", Culture)!;

    public static string TrackCatalog_ClearSearch =>
        ResourceManager.GetString("TrackCatalog_ClearSearch", Culture)!;

    // Dance Tree
    public static string DanceTree_MarkRootRandom =>
        ResourceManager.GetString("DanceTree_MarkRootRandom", Culture)!;

    public static string DanceTree_MarkRandom =>
        ResourceManager.GetString("DanceTree_MarkRandom", Culture)!;

    public static string DanceTree_AddCategory =>
        ResourceManager.GetString("DanceTree_AddCategory", Culture)!;

    public static string DanceTree_AddDance =>
        ResourceManager.GetString("DanceTree_AddDance", Culture)!;

    public static string DanceTree_Confirm =>
        ResourceManager.GetString("DanceTree_Confirm", Culture)!;

    public static string DanceTree_Edit =>
        ResourceManager.GetString("DanceTree_Edit", Culture)!;

    public static string DanceTree_Cancel =>
        ResourceManager.GetString("DanceTree_Cancel", Culture)!;

    public static string DanceTree_Delete =>
        ResourceManager.GetString("DanceTree_Delete", Culture)!;

    public static string DanceTree_RootName =>
        ResourceManager.GetString("DanceTree_RootName", Culture)!;

    public static string DanceTree_NoTracksAvailable =>
        ResourceManager.GetString("DanceTree_NoTracksAvailable", Culture)!;

    public static string DanceTree_NameEmpty =>
        ResourceManager.GetString("DanceTree_NameEmpty", Culture)!;

    public static string DanceTree_CategoryNameExists =>
        ResourceManager.GetString("DanceTree_CategoryNameExists", Culture)!;

    public static string DanceTree_DanceNameExists =>
        ResourceManager.GetString("DanceTree_DanceNameExists", Culture)!;

    // Dance Tree Toolbar
    public static string DanceTreeToolbar_SwitchToTrackList =>
        ResourceManager.GetString("DanceTreeToolbar_SwitchToTrackList", Culture)!;

    public static string DanceTreeToolbar_ImportDanceTree =>
        ResourceManager.GetString("DanceTreeToolbar_ImportDanceTree", Culture)!;

    public static string DanceTreeToolbar_ExportDanceTree =>
        ResourceManager.GetString("DanceTreeToolbar_ExportDanceTree", Culture)!;

    public static string DanceTreeToolbar_ImportTitle =>
        ResourceManager.GetString("DanceTreeToolbar_ImportTitle", Culture)!;

    public static string DanceTreeToolbar_ImportConfirmMessage =>
        ResourceManager.GetString("DanceTreeToolbar_ImportConfirmMessage", Culture)!;

    public static string DanceTreeToolbar_ImportButton =>
        ResourceManager.GetString("DanceTreeToolbar_ImportButton", Culture)!;

    public static string DanceTreeToolbar_CancelButton =>
        ResourceManager.GetString("DanceTreeToolbar_CancelButton", Culture)!;

    public static string DanceTreeToolbar_ExportTitle =>
        ResourceManager.GetString("DanceTreeToolbar_ExportTitle", Culture)!;

    public static string DanceTreeToolbar_UndoFormat =>
        ResourceManager.GetString("DanceTreeToolbar_UndoFormat", Culture)!;

    public static string DanceTreeToolbar_UndoDefault =>
        ResourceManager.GetString("DanceTreeToolbar_UndoDefault", Culture)!;

    public static string DanceTreeToolbar_RedoFormat =>
        ResourceManager.GetString("DanceTreeToolbar_RedoFormat", Culture)!;

    public static string DanceTreeToolbar_RedoDefault =>
        ResourceManager.GetString("DanceTreeToolbar_RedoDefault", Culture)!;

    // Dance Synonyms
    public static string DanceSynonyms_Title =>
        ResourceManager.GetString("DanceSynonyms_Title", Culture)!;

    public static string DanceSynonyms_Back =>
        ResourceManager.GetString("DanceSynonyms_Back", Culture)!;

    public static string DanceSynonyms_ImportSynonyms =>
        ResourceManager.GetString("DanceSynonyms_ImportSynonyms", Culture)!;

    public static string DanceSynonyms_ExportSynonyms =>
        ResourceManager.GetString("DanceSynonyms_ExportSynonyms", Culture)!;

    public static string DanceSynonyms_AddNewDance =>
        ResourceManager.GetString("DanceSynonyms_AddNewDance", Culture)!;

    public static string DanceSynonyms_DanceNameWatermark =>
        ResourceManager.GetString("DanceSynonyms_DanceNameWatermark", Culture)!;

    public static string DanceSynonyms_SynonymWatermark =>
        ResourceManager.GetString("DanceSynonyms_SynonymWatermark", Culture)!;

    public static string DanceSynonyms_Edit =>
        ResourceManager.GetString("DanceSynonyms_Edit", Culture)!;

    public static string DanceSynonyms_Confirm =>
        ResourceManager.GetString("DanceSynonyms_Confirm", Culture)!;

    public static string DanceSynonyms_Delete =>
        ResourceManager.GetString("DanceSynonyms_Delete", Culture)!;

    public static string DanceSynonyms_Cancel =>
        ResourceManager.GetString("DanceSynonyms_Cancel", Culture)!;

    public static string DanceSynonyms_AddSynonym =>
        ResourceManager.GetString("DanceSynonyms_AddSynonym", Culture)!;

    public static string DanceSynonyms_NameEmpty =>
        ResourceManager.GetString("DanceSynonyms_NameEmpty", Culture)!;

    public static string DanceSynonyms_NameInUse =>
        ResourceManager.GetString("DanceSynonyms_NameInUse", Culture)!;

    public static string DanceSynonyms_ImportTitle =>
        ResourceManager.GetString("DanceSynonyms_ImportTitle", Culture)!;

    public static string DanceSynonyms_ImportConfirmMessage =>
        ResourceManager.GetString("DanceSynonyms_ImportConfirmMessage", Culture)!;

    public static string DanceSynonyms_ImportButton =>
        ResourceManager.GetString("DanceSynonyms_ImportButton", Culture)!;

    public static string DanceSynonyms_CancelButton =>
        ResourceManager.GetString("DanceSynonyms_CancelButton", Culture)!;

    public static string DanceSynonyms_ImportFilePickerTitle =>
        ResourceManager.GetString("DanceSynonyms_ImportFilePickerTitle", Culture)!;

    public static string DanceSynonyms_ExportFilePickerTitle =>
        ResourceManager.GetString("DanceSynonyms_ExportFilePickerTitle", Culture)!;

    public static string DanceSynonyms_UndoFormat =>
        ResourceManager.GetString("DanceSynonyms_UndoFormat", Culture)!;

    public static string DanceSynonyms_UndoDefault =>
        ResourceManager.GetString("DanceSynonyms_UndoDefault", Culture)!;

    public static string DanceSynonyms_RedoFormat =>
        ResourceManager.GetString("DanceSynonyms_RedoFormat", Culture)!;

    public static string DanceSynonyms_RedoDefault =>
        ResourceManager.GetString("DanceSynonyms_RedoDefault", Culture)!;

    // Presentation
    public static string Presentation_WindowTitle =>
        ResourceManager.GetString("Presentation_WindowTitle", Culture)!;

    public static string Presentation_NoTrackPlaying =>
        ResourceManager.GetString("Presentation_NoTrackPlaying", Culture)!;

    public static string Presentation_Next =>
        ResourceManager.GetString("Presentation_Next", Culture)!;

    public static string Presentation_NoNextTrack =>
        ResourceManager.GetString("Presentation_NoNextTrack", Culture)!;

    public static string Presentation_Delay =>
        ResourceManager.GetString("Presentation_Delay", Culture)!;

    public static string Presentation_Stop =>
        ResourceManager.GetString("Presentation_Stop", Culture)!;

    public static string Presentation_Message =>
        ResourceManager.GetString("Presentation_Message", Culture)!;

    // Dialogs
    public static string Dialog_RequestMessageTitle =>
        ResourceManager.GetString("Dialog_RequestMessageTitle", Culture)!;

    public static string Dialog_MessageLabel =>
        ResourceManager.GetString("Dialog_MessageLabel", Culture)!;

    public static string Dialog_MessageWatermark =>
        ResourceManager.GetString("Dialog_MessageWatermark", Culture)!;

    public static string Dialog_UseTimedDelay =>
        ResourceManager.GetString("Dialog_UseTimedDelay", Culture)!;

    public static string Dialog_DelayDuration =>
        ResourceManager.GetString("Dialog_DelayDuration", Culture)!;

    public static string Dialog_Cancel =>
        ResourceManager.GetString("Dialog_Cancel", Culture)!;

    public static string Dialog_OK =>
        ResourceManager.GetString("Dialog_OK", Culture)!;

    public static string Dialog_ConfirmDefault =>
        ResourceManager.GetString("Dialog_ConfirmDefault", Culture)!;

    public static string Dialog_YesDefault =>
        ResourceManager.GetString("Dialog_YesDefault", Culture)!;

    public static string Dialog_NoDefault =>
        ResourceManager.GetString("Dialog_NoDefault", Culture)!;

    public static string Dialog_AreYouSure =>
        ResourceManager.GetString("Dialog_AreYouSure", Culture)!;

    public static string Dialog_CharacterCountFormat =>
        ResourceManager.GetString("Dialog_CharacterCountFormat", Culture)!;

    // App
    public static string App_ExitTitle =>
        ResourceManager.GetString("App_ExitTitle", Culture)!;

    public static string App_ExitMessage =>
        ResourceManager.GetString("App_ExitMessage", Culture)!;

    public static string Settings_LanguageRestartTitle =>
        ResourceManager.GetString("Settings_LanguageRestartTitle", Culture)!;

    public static string Settings_LanguageRestartMessage =>
        ResourceManager.GetString("Settings_LanguageRestartMessage", Culture)!;

    public static string Dialog_Restart =>
        ResourceManager.GetString("Dialog_Restart", Culture)!;
}
